## Use an official Java image
#FROM eclipse-temurin:21
#
## Set the working directory inside the container
#WORKDIR /app
#
#LABEL mentainer="santhoshsanthi9455@gmail.com"
#
## Copy the jar file into the container
#COPY target/SRS-0.0.1-SNAPSHOT.jar /app/SRS-docker.jar
#
#
## Expose the app port
#EXPOSE 8080
#
## Run the app
#ENTRYPOINT ["java", "-jar", "SRS-docker.jar"]
